module.exports = {
	USER_CONNECTED:"USER_CONNECTED",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	VERIFY_USER:"VERIFY_USER",
	LOGOUT:"LOGOUT",
	LETTER_UPDATE:"LETTER_UPDATE",
	WORD_CHALLENGED:"WORD_CHALLENGED",
	PLAYER_SUCCESSFUL: "PLAYER_SUCCESSFUL",
	PLAYER_UNSUCCESSFUL: "PLAYER_UNSUCCESSFUL",
	YOUR_TURN: "YOUR_TURN",
	SEND_MODAL: "SEND_MODAL",
	NEW_ROOM: "NEW_ROOM"
}